In [1]:
import pandas as pd 
import numpy as np

In [2]:
data = np.random.randn(4,3)
data

array([[-0.34996122, -0.45881956,  1.47145342],
       [ 0.30990206,  0.99370322, -0.64025476],
       [-2.01614243, -1.09117773,  0.90747544],
       [-0.39556677,  0.91944219, -0.32500437]])

In [3]:
data_frame = pd.DataFrame(data)
data_frame

          0         1         2
0 -0.349961 -0.458820  1.471453
1  0.309902  0.993703 -0.640255
2 -2.016142 -1.091178  0.907475
3 -0.395567  0.919442 -0.325004

In [4]:
type(data_frame)

pandas.core.frame.DataFrame

In [5]:
data_frame[0]

0   -0.349961
1    0.309902
2   -2.016142
3   -0.395567
Name: 0, dtype: float64

In [6]:
type(data_frame[0])

pandas.core.series.Series

In [7]:
new_df = pd.DataFrame(data,index = ["Atil","Zeynep","Atlas","Mehmet"],columns=["Salary","Age","Seniority"])

In [8]:
new_df

          Salary       Age  Seniority
Atil   -0.349961 -0.458820   1.471453
Zeynep  0.309902  0.993703  -0.640255
Atlas  -2.016142 -1.091178   0.907475
Mehmet -0.395567  0.919442  -0.325004

In [9]:
new_df["Age"]

Atil     -0.458820
Zeynep    0.993703
Atlas    -1.091178
Mehmet    0.919442
Name: Age, dtype: float64

In [10]:
new_df["Salary"]

Atil     -0.349961
Zeynep    0.309902
Atlas    -2.016142
Mehmet   -0.395567
Name: Salary, dtype: float64

In [11]:
new_df[["Age","Salary"]]

             Age    Salary
Atil   -0.458820 -0.349961
Zeynep  0.993703  0.309902
Atlas  -1.091178 -2.016142
Mehmet  0.919442 -0.395567

In [12]:
# row da ki değere ulaşmak istersek loc (location) kullanılır / iloc(indexe göre location)

In [13]:
new_df.loc["Atil"]

Salary      -0.349961
Age         -0.458820
Seniority    1.471453
Name: Atil, dtype: float64

In [14]:
new_df.iloc[0]

Salary      -0.349961
Age         -0.458820
Seniority    1.471453
Name: Atil, dtype: float64

In [15]:
new_df.iloc[1]

Salary       0.309902
Age          0.993703
Seniority   -0.640255
Name: Zeynep, dtype: float64

In [16]:
# : => bütün rowları seç demek

In [17]:
new_df.iloc[:,1]

Atil     -0.458820
Zeynep    0.993703
Atlas    -1.091178
Mehmet    0.919442
Name: Age, dtype: float64

In [18]:
# Column ekleme - silme

In [19]:
new_df["Extra"] = 10

In [20]:
new_df

          Salary       Age  Seniority  Extra
Atil   -0.349961 -0.458820   1.471453     10
Zeynep  0.309902  0.993703  -0.640255     10
Atlas  -2.016142 -1.091178   0.907475     10
Mehmet -0.395567  0.919442  -0.325004     10

In [21]:
new_df.drop("Extra",axis=1)

          Salary       Age  Seniority
Atil   -0.349961 -0.458820   1.471453
Zeynep  0.309902  0.993703  -0.640255
Atlas  -2.016142 -1.091178   0.907475
Mehmet -0.395567  0.919442  -0.325004

In [22]:
new_df

          Salary       Age  Seniority  Extra
Atil   -0.349961 -0.458820   1.471453     10
Zeynep  0.309902  0.993703  -0.640255     10
Atlas  -2.016142 -1.091178   0.907475     10
Mehmet -0.395567  0.919442  -0.325004     10

In [23]:
# axis = 0 => row için işlem yap / axis = 1 => column için işlem yap
# inplace => ayrı bir dataframe döndürme işlemi aynı data frame için gerçekleştir.

In [24]:
new_df.drop("Extra",axis=1,inplace=True)
new_df

          Salary       Age  Seniority
Atil   -0.349961 -0.458820   1.471453
Zeynep  0.309902  0.993703  -0.640255
Atlas  -2.016142 -1.091178   0.907475
Mehmet -0.395567  0.919442  -0.325004

In [25]:
new_df["Mehmet"] = 10

In [26]:
new_df

          Salary       Age  Seniority  Mehmet
Atil   -0.349961 -0.458820   1.471453      10
Zeynep  0.309902  0.993703  -0.640255      10
Atlas  -2.016142 -1.091178   0.907475      10
Mehmet -0.395567  0.919442  -0.325004      10

In [27]:
new_df.drop("Mehmet")

          Salary       Age  Seniority  Mehmet
Atil   -0.349961 -0.458820   1.471453      10
Zeynep  0.309902  0.993703  -0.640255      10
Atlas  -2.016142 -1.091178   0.907475      10

In [28]:
new_df.drop("Mehmet",axis=1,inplace=True)

In [29]:
new_df

          Salary       Age  Seniority
Atil   -0.349961 -0.458820   1.471453
Zeynep  0.309902  0.993703  -0.640255
Atlas  -2.016142 -1.091178   0.907475
Mehmet -0.395567  0.919442  -0.325004

In [30]:
new_df.loc["Atlas"]

Salary      -2.016142
Age         -1.091178
Seniority    0.907475
Name: Atlas, dtype: float64

In [31]:
new_df.loc["Atlas"]["Salary"]

np.float64(-2.016142433027164)

In [32]:
new_df.loc["Atlas","Salary"]

np.float64(-2.016142433027164)

In [33]:
new_df.loc["Atlas","Salary"] = 100

In [34]:
new_df

            Salary       Age  Seniority
Atil     -0.349961 -0.458820   1.471453
Zeynep    0.309902  0.993703  -0.640255
Atlas   100.000000 -1.091178   0.907475
Mehmet   -0.395567  0.919442  -0.325004

In [35]:
new_df > 0

        Salary    Age  Seniority
Atil     False  False       True
Zeynep    True   True      False
Atlas     True  False       True
Mehmet   False   True      False

In [36]:
new_df[new_df > 0]

            Salary       Age  Seniority
Atil           NaN       NaN   1.471453
Zeynep    0.309902  0.993703        NaN
Atlas   100.000000       NaN   0.907475
Mehmet         NaN  0.919442        NaN

In [37]:
new_df[new_df["Salary"] > 1]

       Salary       Age  Seniority
Atlas   100.0 -1.091178   0.907475

In [38]:
# Dataframe Indexing

In [39]:
new_df.reset_index()

    index      Salary       Age  Seniority
0    Atil   -0.349961 -0.458820   1.471453
1  Zeynep    0.309902  0.993703  -0.640255
2   Atlas  100.000000 -1.091178   0.907475
3  Mehmet   -0.395567  0.919442  -0.325004

In [40]:
reset_frame = new_df.reset_index()

In [41]:
reset_frame

    index      Salary       Age  Seniority
0    Atil   -0.349961 -0.458820   1.471453
1  Zeynep    0.309902  0.993703  -0.640255
2   Atlas  100.000000 -1.091178   0.907475
3  Mehmet   -0.395567  0.919442  -0.325004

In [42]:
reset_frame.loc[0]

index            Atil
Salary      -0.349961
Age          -0.45882
Seniority    1.471453
Name: 0, dtype: object

In [43]:
new_indices = ["Atil","Zey","Atl","Meh"]

In [44]:
new_df["NewIndex"] = new_indices

In [45]:
new_df

            Salary       Age  Seniority NewIndex
Atil     -0.349961 -0.458820   1.471453     Atil
Zeynep    0.309902  0.993703  -0.640255      Zey
Atlas   100.000000 -1.091178   0.907475      Atl
Mehmet   -0.395567  0.919442  -0.325004      Meh

In [46]:
new_df.set_index("NewIndex",inplace=True)

In [47]:
new_df

              Salary       Age  Seniority
NewIndex
Atil       -0.349961 -0.458820   1.471453
Zey         0.309902  0.993703  -0.640255
Atl       100.000000 -1.091178   0.907475
Meh        -0.395567  0.919442  -0.325004

In [48]:
new_df.loc["Atil"]

Salary      -0.349961
Age         -0.458820
Seniority    1.471453
Name: Atil, dtype: float64

In [49]:
# multi index

In [50]:
first_index = ["Simpson","Simpson","Simpson","South Park","South Park","South Park"]
inner_index = ["Homer","Bard","Merge","Cartman","Kenny","Kyle"]
zipped_index = list(zip(first_index,inner_index))
zipped_index

[('Simpson', 'Homer'),
 ('Simpson', 'Bard'),
 ('Simpson', 'Merge'),
 ('South Park', 'Cartman'),
 ('South Park', 'Kenny'),
 ('South Park', 'Kyle')]

In [51]:
zipped_index = pd.MultiIndex.from_tuples(zipped_index)

In [52]:
zipped_index

MultiIndex([(   'Simpson',   'Homer'),
            (   'Simpson',    'Bard'),
            (   'Simpson',   'Merge'),
            ('South Park', 'Cartman'),
            ('South Park',   'Kenny'),
            ('South Park',    'Kyle')],
           )

In [53]:
sample_values = np.ones((6,2))

In [54]:
big_df = pd.DataFrame(sample_values,index=zipped_index,columns=["Age","Salary"])
big_df

                    Age  Salary
Simpson    Homer    1.0     1.0
           Bard     1.0     1.0
           Merge    1.0     1.0
South Park Cartman  1.0     1.0
           Kenny    1.0     1.0
           Kyle     1.0     1.0

In [55]:
big_df["Age"]

Simpson     Homer      1.0
            Bard       1.0
            Merge      1.0
South Park  Cartman    1.0
            Kenny      1.0
            Kyle       1.0
Name: Age, dtype: float64

In [56]:
big_df.loc["Simpson"].loc["Homer"]

Age       1.0
Salary    1.0
Name: Homer, dtype: float64